[boris]
  version = 1

[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "corba-core"]]

[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "corba-core"]]

[build.dist-7-10-cli]
  command = [["master", "build", "dist-7-10", "-C", "corba-cli"]]

[build.branches-7-10-cli]
  command = [["master", "build", "branches-7-10", "-C", "corba-cli"]]


[build.dist-8-0-core]
  command = [["master", "build", "dist-8-0", "-C", "corba-core"]]

[build.branches-8-0-core]
  command = [["master", "build", "branches-8-0", "-C", "corba-core"]]

[build.dist-8-0-cli]
  command = [["master", "build", "dist-8-0", "-C", "corba-cli"]]

[build.branches-8-0-cli]
  command = [["master", "build", "branches-8-0", "-C", "corba-cli"]]


[build.dist-validate]
  command = [["validate-respect"]]

[build.all-submodules]
  command = [["dangling-refs"]]

[build.all-rebased]
  command = [["rebased"]]
